apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-service-label
  template:
    metadata:
      labels:
        app: go-service-label
    spec:
      restartPolicy: Always
      initContainers:
        - name: go-service-migrate
          image: ntsd/go-service-migrate:latest
          env:
            - name: GOMAXPROCS
              value: "1"
            - name: POSTGRES_URL
              value: "postgresql://postgres:password@postgres-service.default.svc.cluster.local:5432/go_service"
      containers:
        - name: go-service
          image: ntsd/go-service:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          env:
            - name: GOMAXPROCS
              value: "1"
            - name: POSTGRES_URL
              value: "postgresql://postgres:password@postgres-service.default.svc.cluster.local:5432/go_service"
            - name: DEV_MODE
              value: "false"
            - name: PREFORK
              value: "false"
            - name: ES256_PRIVATE_KEY
              value: "./deployments/ec_private.pem"
            - name: ES256_PUBLIC_KEY
              value: "./deployments/ec_public.pem"
            - name: APP_PORT
              value: "8080"
