apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
