apiVersion: v1
kind: Service
metadata:
  name: go-service-service
spec:
  type: ClusterIP
  ports:
    - name: go-service-port
      port: 8080 # service port
      targetPort: 8080 # container port
      protocol: TCP
  selector:
    app: go-service-label
