apiVersion: v1
kind: Service
metadata:
  name: go-service-service
spec:
  type: LoadBalancer
  clusterIP: 10.101.210.30
  ports:
    - name: go-service-port
      port: 8080 # service port
      targetPort: 8080 # container port
      protocol: TCP
  selector:
    tag: go-service-label
