// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/crypto/jwt.go

// Package mock_crypto is a generated GoMock package.
package mock_crypto

import (
	models "go-service/internal/models"
	reflect "reflect"
	time "time"

	jwt "github.com/golang-jwt/jwt"
	gomock "github.com/golang/mock/gomock"
)

// MockJWTFactory is a mock of JWTFactory interface.
type MockJWTFactory struct {
	ctrl     *gomock.Controller
	recorder *MockJWTFactoryMockRecorder
}

// MockJWTFactoryMockRecorder is the mock recorder for MockJWTFactory.
type MockJWTFactoryMockRecorder struct {
	mock *MockJWTFactory
}

// NewMockJWTFactory creates a new mock instance.
func NewMockJWTFactory(ctrl *gomock.Controller) *MockJWTFactory {
	mock := &MockJWTFactory{ctrl: ctrl}
	mock.recorder = &MockJWTFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTFactory) EXPECT() *MockJWTFactoryMockRecorder {
	return m.recorder
}

// GenerateJWT mocks base method.
func (m *MockJWTFactory) GenerateJWT(client *models.Client, duration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT", client, duration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockJWTFactoryMockRecorder) GenerateJWT(client, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockJWTFactory)(nil).GenerateJWT), client, duration)
}

// ValidateJWT mocks base method.
func (m *MockJWTFactory) ValidateJWT(tokenString string) (*jwt.StandardClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateJWT", tokenString)
	ret0, _ := ret[0].(*jwt.StandardClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateJWT indicates an expected call of ValidateJWT.
func (mr *MockJWTFactoryMockRecorder) ValidateJWT(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateJWT", reflect.TypeOf((*MockJWTFactory)(nil).ValidateJWT), tokenString)
}
