# using bitnami/postgres https://hub.docker.com/r/bitnami/postgresql for master/slave mode
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-master-label
  template:
    metadata:
      labels:
        app: postgres-master-label
    spec:
      containers:
        - name: postgres-master
          image: bitnami/postgresql:15.3.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DATABASE
              value: "go_service"
            - name: POSTGRESQL_REPLICATION_MODE
              value: "master"
            - name: POSTGRESQL_REPLICATION_USER
              value: "my_repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "my_repl_password"
            
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
spec:
  selector:
    app: postgres-master-label
  type: ClusterIP
  ports:
    - name: postgres-port
      port: 5432
